some changes use java NIO
rup-projects/plantuml-generator pull request #1
Opened 2020-09-05 16:08 UTC by Ruskab

2020-09-05 16:30 UTC, plfgavilan requested changes

2020-09-05 16:30 UTC, plfgavilan commented on documentation/requirementview/usecases.puml
> +User --> (generate puml class diagrams)
Me gusta más un nombre qué una frase. Para mí ClassDiagramGenerator sería el nombre del caso de uso y tiene trazabilidad como el nombre de un controlador, y lo que tu has puesto podría ser más bien descripción

2020-09-05 16:30 UTC, plfgavilan commented on documentation/analisysview/collaborations/ClassDiagramGenerator.puml
> +!include definitions.puml
Los includes se pueden añadir por defecto con intellij o la herramienta de visualización y así no hace falta mantenerlos en cada puml

![image](https://user-images.githubusercontent.com/4791544/92309174-8519f500-efa3-11ea-98ae-941f9c9ef2ef.png)

2020-09-05 16:30 UTC, plfgavilan commented on src/main/java/org/rup/pumlgenerator/controllers/FileUtilsFacade.java
> +    public List<File> readFilesFromDirectory(Path directory) throws IOException {
Esto está muy guay :+1:

2020-09-05 16:30 UTC, plfgavilan commented on src/main/java/org/rup/pumlgenerator/controllers/FileUtilsFacade.java
> +    public List<String> convertFilesToString(List<File> files) {
Mucho mas directo :+1:

2020-09-05 16:30 UTC, plfgavilan commented on src/main/java/org/rup/pumlgenerator/daos/PumlClassDao.java
>              System.out.println("Error generating file for: " + pumlClass);
Aquí mejor con log.error("Error generation file for", e)

2020-09-05 16:30 UTC, plfgavilan commented on src/main/java/org/rup/pumlgenerator/utils/Extensions.java
> +public class Extensions {
Para qué usas esto?

2020-09-05 16:30 UTC, plfgavilan commented on src/main/java/org/rup/pumlgenerator/utils/throwingfunctions/ThrowingFunction.java
> +public interface ThrowingFunction<T, R, E extends Throwable> {
Misma pregunta

2020-09-05 16:30 UTC, plfgavilan commented on documentation/analisysview/collaborations/ClassDiagramGenerator.puml
> +!include definitions.puml
@Ruskab  como acabamos de hablar, dejemos los includes entonces. PAra que si cualquiera se clona el proyecto, que le funcione directamente

2020-09-05 16:56 UTC, Ruskab commented on src/main/java/org/rup/pumlgenerator/utils/Extensions.java
> +public class Extensions {
ostras pensaba que no lo subi xDDD era una prueba 

el problema:

        return files.stream()
                .map(File::toPath)
                .flatMap(Files::lines)
                .filter(Strings::isNotBlank)
                .collect(Collectors.toList());
    }

Files::lines --> lanza una checked exception, que si usas landas te obliga a meter un try catch por enmedio to feo, 

y buscando que soluciones pone la gente, habia una que era usando [extended methods de de lombok](https://medium.com/@yassinhajaj/write-java-streams-with-checked-exception-safe-lambdas-5d0d78217867) (hoy descubro que existe lombok, y encima tiene solucion para ese problema en concreto jaja)

basicamente extender la API de Stream con tu propio metodo que tenga encuenta las checked exceptions.

y probe implementarlo, pero no lo consegui, a lo mejor iba pero Intellij no me reconocia ese metodo mapUnchecked.


La alternativa a esta solucion es ThrowingFuncion

2020-09-05 17:03 UTC, Ruskab commented on src/main/java/org/rup/pumlgenerator/utils/throwingfunctions/ThrowingFunction.java
> +public interface ThrowingFunction<T, R, E extends Throwable> {
return files.stream()
                .map(File::toPath)
                .flatMap(ThrowingFunction.unchecked(Files::lines))
                .filter(Strings::isNotBlank)
                .collect(Collectors.toList());

Es por este metodo, te obliga meter el try catch en el FIles.lines() por que puede lanzar un IOException,  y te lo enguararia todo meterlo por en medio, existe este , [workoround para evitarlo](https://dzone.com/articles/how-to-handle-checked-exception-in-lambda-expressi?utm_source=DZone&utm_medium=article&utm_campaign=Java%208) es la primera vez que lo pruebo la verdad

2020-09-05 17:04 UTC, Ruskab commented on src/main/java/org/rup/pumlgenerator/daos/PumlClassDao.java
>              System.out.println("Error generating file for: " + pumlClass);
yeep, seria merjo 👍

2020-09-05 17:18 UTC, Ruskab commented on documentation/requirementview/usecases.puml
> +User --> (generate puml class diagrams)
entiendo si, lo dejamos como ClassDiagramGenerator , perfecto

2020-09-07 17:51 UTC, plfgavilan approved these changes

2020-10-04 17:21 UTC, merged